pdata<-read.table("household_power_consumption.txt", header = TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
pdata1<-pdata[pdata$Date %in% c("1/2/2007", "2/2/2007"),]
dataday <- strptime(paste(pdata1$Date, pdata1$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot3.png", width=480, height=480)
plot(dataday, as.numeric(pdata1$sub_metering_1), type="l", ylab="Energy Submetering", xlab="")
lines(dataday, as.numeric(pdata1$sub_metering_2), type="l", col="geen")
lines(dataday, as.numeric(pdata1$sub_metering_3), type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "green", "blue"))
dev.off()

plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
+lines(datetime, subMetering2, type="l", col="red")
+lines(datetime, subMetering3, type="l", col="blue")
+legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
+dev.off() 